# ベースイメージを指定（Ruby 3.4.10）
FROM ruby:3.4.10

# 日本語対応の環境変数設定
ENV LANG C.UTF-8
# タイムゾーンを日本に設定
ENV TZ Asia/Tokyo

# Node.js 20をインストールできるように公式リポジトリを登録
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# Rails開発に必要なパッケージをインストール
# corepack有効化(yarnやpnpmを利用可に設定)
# aptのパッケージ一覧キャッシュを削除
RUN apt-get update -qq \
&& apt-get install -y build-essential libpq-dev nodejs vim \
&& corepack enable \
&& rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリをコンテナ内に作成
RUN mkdir /myapp
# アプリケーションディレクトリに移動（コンテナ内）
WORKDIR /myapp

# Bundlerをインストール（Rubyのパッケージ管理ツール）
RUN gem install bundler
# ホスト側のアプリケーションのコードをコンテナ内にコピー
COPY . /myapp
